### Obtener todas las notificaciones NO archivadas
GET http://localhost:3000/api/notifications/unfiled

### Obtener una notificación por ID
GET http://localhost:3000/api/notifications/67c3bb18836aea9d621e6d9e

### Obtener todas las notificaciones archivadas
GET http://localhost:3000/api/notifications/filed

### Obtener una notificación archivada por ID
GET http://localhost:3000/api/notifications/filed/67c3bb18836aea9d621e6d9e

### Crear una notificación
POST http://localhost:3000/api/notifications
Content-Type: application/json

{
    "name": "High Temperature Alert",
    "date": "2025-03-15T14:30:00Z",
    "sensor": "Temperature Sensor",
    "device": "67c3bb18836aea9d621e6d9f",
    "image": "https://example.com/image.jpg",
    "status": true
}

### Archivar una notificación
PUT http://localhost:3000/api/notifications/filed/67c3bb18836aea9d621e6d9e
Content-Type: application/json

{
    "status": false
}
